name: CI Workflow

on:
  push:
    branches:
      - main  # Esto se activa cuando se hace un push a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Ejecuta en una máquina virtual con Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Este paso descarga el código del repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Especifica la versión de Node.js a usar

      - name: Install dependencies
        run: |
          npm install  # Instala dependencias (si las tienes en package.json)

      - name: Run Hello World script
        run: node hello_world.js  # Ejecuta el archivo hello_world.js
